name: CI Tests Reusable Workflow

on:
  workflow_call:
    inputs:
      run-version-check:
        type: boolean

jobs:

  test:
    name: Test (Project Python Version)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        run: uv sync --all-extras
      - name: Run tests with coverage
        run: uv run pytest -v