name: Allow merges only from selected branches

on:
  workflow_call:
    inputs:
      branch_name:
        type: string
        required: false
        default: dev
        description: "Branch name that is allowed to merge"

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Comment PR
      if: github.head_ref != inputs.branch_name
      uses: thollander/actions-comment-pull-request@v3
      with:
        message: |
          "Error: Pull request must come from '${{ inputs.branch_name }}' branch, but come from '${{ github.head_ref }}'"

    - name: Check branch
      if: github.head_ref != inputs.branch_name
      run: |
        echo "Error: Pull request must come from '${{ inputs.branch_name }}' branch, but come from '${{ github.head_ref }}'"
        exit 1
