name: CI Tests Reusable Workflow

on:
  workflow_call:
    inputs:
      run-version-check:
        type: boolean

jobs:

  test:
    name: Test (Project Python Version)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"

      - name: Set up Python
        run: uv sync --all-extras
      - name: Run tests with coverage
        run: uv run pytest -v
      - name: Run app tests
        if: hashFiles('app_src/pyproject.toml') != '' && hashFiles('app_src/tests/**/*.py') != ''
        run: uv run --directory app_src pytest -v