name: Release

on:
  push:
    branches: 
      - main
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/cdk_ci_workflow_cdk.yml
    with:
      run-version-check: false
  cd:
    needs: ci
    uses: ./.github/workflows/cdk_cd_workflow_cdk.yml
